### ISSUE TITLE
how do i install this?

### ISSUE THREAD

**Issue by timini** [restaumatic/vcr-proxy#9]
i want to use it but how?

**Comment by kozak** [comment]
Hi! 
If you are using haskell, the easiest way is to  build it with `stack install` (this will put the binary into `$HOME/.local/bin` which you might want to add to your path). 
If you are not using haskell, we are building a binary(this is build on Ubuntu latest): https://github.com/restaumatic/vcr-proxy/releases/tag/v0.3.0.0

**Comment by timini** [comment]
thanks for the readme update! 

installation worked fine with the binary
